# ----------------------------------------------------------------------------
#
# config
#
# ----------------------------------------------------------------------------

sudo: false
language: python

# we only care about the docs branch
branches:
    only:
        - docs

# notify srcc#github
notifications:
    slack:
        secure: b8qQVB4C8u0pOBh8M/+jeNl5B9aIJB0VyxmOCVRn5AT8RAlnj805eY+RAq1THSIwPGJXeQ5lY3tLKXvRGSp3bfjY5DSrSloJS879WL4BCMzOT+o+v+YQzkICn5E5x+Sz4C/PWScR4UR9iUSTb37PAYCPATc9l/+hI/XO2jNBi0hDOWOYVfd1erGPMJOGBhJCfz0gdu5ULJ5QLbvjGIWXfOgsHG/DRfEMvnpuaW1Gi+g+RFeA1II0ZN/44n2UENiM+nmJTcjmQaJ+6yBxxXmWwIgKc4SqI4zoHIkz3Zck88m4RIe7tzj5HHwI/T6h7G5FJPojbL6J9YWqceSZF+q0VwLgVitStrDsGG34eVxQG1Cp5p8rltHGSjr2kGpdb7Nh9IOV2C6FcfoyY8X3ZrGGfzN3RwNO6nFNtEJ4MN1yJRrmOClJmDIGolloNwUpTr6ZgzhOC07ydNX6oTqj4gqCxqYmGX07oc2sCN1nwb5WPtQXpkafYTThUnKVunoomrps+EOCNjL6j3g/TYo9w1rKxnnUA2mxuRlDYGn2PcMs8RJOpbFkDIX7EYyEIiLAI0H8PUUHgsdC6kX9z6W91RXCV7scxLi0xNFZ4l/9Relg7YfGwQjCJNcU4um1BZonEVpqosht5PU3moqdIvxdVOIn5avJ9nqJLzi+Ic8bBnO6eWo=


# ----------------------------------------------------------------------------
#
# build
#
# ----------------------------------------------------------------------------

# limit clone depth to 50, to speed up build
git:
    depth: 50

before_install:
    - |
      # check that we actually need to build anything
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(README.md)|(^(\.git|site))/' || {
          echo "Only non-source files were updated, no need to trigger a build."
          exit
      }

# install dependencies
install:
    - pip install mkdocs
    - pip install -r requirements.txt

# build
script:
    - mkdocs build --verbose --clean

# ----------------------------------------------------------------------------
#
# deployment
#
# ----------------------------------------------------------------------------

# deploy
#   fetch "docs" branch and copy contents of material/ there, then commit and push

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $DEPLOY_KEY # Set in travis-ci.com dashboard
    local-dir: site
    target_branch: gh-pages   # that's the default, but just to make sure
    fqdn: www.sherlock.stanford.edu
    #fqdn: 117f8628f187c24bbe15febead3046fa.sherlock.stanford.edu # temporary stealthy URL
    project-name: "Sherlock documentation"
    on:
        branch: docs
    verbose: true
    edge:
        branch: v1.8.47
