# ----------------------------------------------------------------------------
#
# config
#
# ----------------------------------------------------------------------------

sudo: false
language: python

# we only care about the docs branch
branches:
    only:
        - docs

# notify srcc#github
notifications:
    slack:
        secure: iWp+s5M7P2oHkSqX92NKxhHRNaH1fZ1j8OHluo6oqiht1aqB2vcHdCeCWNS8GQBFNBf5DAMkD1tKiIJPdonCkMVoizv0lvwemx+U6RWMZpL4+E3YOLxAh1thtcKqAdcs549eEdSeAjaylyend6XJI7tU6KPYfbd/dY1xu3Fyt23gqbot55EYlc2Yl0MzsP3AiiDAQ6+ToZfA5r1hWww9Zr9lr3Yt348G8Ti8VXMhiJRwUJ21WCoWnZcBji+AhE0KCY1VP4+VVWL48rQL6CGRwaXkQCyBtw7Pa5U9DUdan4+zrrNSFCxrVSHHPxXAvbAgzWFT0EthW2qO7RCug1BryoucvTn5Mx4Gf8F6UUYJAKairmNiM0AKlck7TP0BM0sFiF2PHorP+s2dJfIXqkx4CNrxz9YxwoFT7q0kiXC9ioKo5cMynYCU0Apcv5mbYnEeh72kCUkPUxZKiOH6ct3aj/91MS6FX9E3YyUHUqES7/j4MEbwzAO+matnq1Wz5w+Nl374+Hmgw03pr8pasTnFWFjIhHuMPS1eg8e5YyFNANlVRp5mxwtG/yhR1lniyiOztd4GG45IARze5tW7vkZSeYghOqZogzfcqDCoJSD/8tViDvpMgXSp0sQg/449DQP8sZ79EfWl0rV6J1MZUSf+N+SrTRXS7tZMtCCza9GvUMI=


# ----------------------------------------------------------------------------
#
# build
#
# ----------------------------------------------------------------------------

# limit clone depth to 50, to speed up build
git:
    depth: 50

before_install:
    - |
      # check that we actually need to build anything
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(README.md)|(INTERNALS.md)|(LICENSE)|(^(\.git|site))/' || {
          echo "Only non-source files were updated, no need to trigger a build."
          exit
      }

# install dependencies
install:
    - pip install mkdocs
    - pip install -r requirements.txt

# build
script:
    - mkdocs build --verbose --clean

# ----------------------------------------------------------------------------
#
# deployment
#
# ----------------------------------------------------------------------------

# deploy
#   fetch "docs" branch and copy contents of material/ there, then commit and push

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $DEPLOY_KEY # Set in travis-ci.com dashboard
    local-dir: site
    target_branch: gh-pages   # that's the default, but just to make sure
    fqdn: www.sherlock.stanford.edu
    #fqdn: 117f8628f187c24bbe15febead3046fa.sherlock.stanford.edu # temporary stealthy URL
    project-name: "Sherlock documentation"
    on:
        branch: docs
    verbose: true
    edge:
        branch: v1.8.47
