# vim: set ts=2 sw=2 sts=2 expandtab:

# Site information
site_name:        Sherlock
site_description: Sherlock Cluster documentation
site_author:      Kilian Cavalotti
site_url:         http://www.sherlock.stanford.edu
site_favicon:     img/logo_small.png

# Repository
#   - repo_url point to the public organization page, so anyone can get to it
#   - edit_url points to the sherlock private repo, so only authorized users can edit content
repo_name:        'SRCC <i class="fa fa-heart-o"></i> Open Source'
repo_url:         'https://github.com/stanford-rc'
edit_uri:         'sherlock/edit/web_docs/src/'

# Copyright
copyright:        "Copyright &copy; 2014 - 2017 &mdash; <a href='mailto:research-computing-support@stanford.edu'>Stanford Research Computing Center</a>"

# Google Analytics
google_analytics: ['UA-68034405-2', auto]

# Documentation and theme directories
docs_dir:   src
site_dir:   site
theme_dir:  theme

# Styling (keep empty values to avoid auto-adding the main page CSS/JS)
extra_css:
  - ''
extra_javascript:
  - ''

# Options
extra:
  feature:
    tabs:   false
  logo:     'img/logo_small.png'
  made_in:  "<a href='https://www.google.com/maps/place/Stanford,+CA'>Stanford, California</a>"
  palette:
    primary: 'stanford'
    accent:  'stanford'
  social:
    - type: 'globe'
      link: 'https:/srcc.stanford.edu'
    - type: 'github'
      link: 'https://github.com/stanford-rc'
    - type: 'twitter'
      link: 'https://twitter.com/StanfordCompute'

# Extensions
markdown_extensions:
  - fontawesome_markdown
  - codehilite:
      guess_lang: False
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: #
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shortener: True
      base_repo_url: https://github.com/stanford-rc/sherlock
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: src/docs/
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: True
  - pymdownx.tilde
  - pymdownx.keys


# Page tree
#
# /!\ IMPORTANT: keep the /docs/ prefix, as /index.html is not managed by mkdocs (landing page)
#
pages:
  - Overview:
    - Introduction:     docs/index.md
    - About:            docs/overview/about.md
    - Concepts:         docs/overview/concepts.md
    - Glossary:         docs/overview/glossary.md
    - Specs:            docs/overview/specs.md
    - Status:           docs/overview/status.md
  - Getting Started:
    - Prerequisites:    docs/getting-started/prerequisites.md
    - Connecting:       docs/getting-started/connecting.md
    - Submitting jobs:  docs/getting-started/submitting.md
  - User guide:
    - Data transfer:    docs/user-guide/data-transfer.md
    - Storage:          docs/user-guide/storage.md
    - Running jobs:     docs/user-guide/running-jobs.md
#    - GPUs:             docs/user-guide/gpus.md
    - Transition to Sherlock 2.0:  docs/user-guide/transition.md
#    - Troubleshooting:  docs/user-guide/troubleshoot.md
  - Software:
    - Overview:         docs/software/overview.md
    - List:             docs/software/list.md
    - Modules:          docs/software/modules.md
    - Installation:     docs/software/install.md
    - Containers:       docs/software/containers.md
    - Using Software:
      - Singularity:    docs/software/using/singularity.md
      - R:              docs/software/using/r.md
      - Python:         docs/software/using/python.md
      - Matlab:         docs/software/using/matlab.md
  - Advanced topics:
    - Connection:       docs/advanced-topics/connection.md
    - Scheduler:        docs/advanced-topics/scheduler.md
    - Owners:           docs/advanced-topics/owners.md

