# vim: set ts=4 sw=4 sts=4 et:

# Site information
site_name:        'Sherlock 2.0'
site_description: 'Sherlock 2.0 Cluster documentation'
site_author:      'Kilian Cavalotti'
site_url:         'http://sherlock2.stanford.edu'
site_favicon:     'images/logo_small.png'

# Repository
repo_url:         'https://github.com/stanford-rc/sherlock'
repo_name:        'github'
edit_uri:         'edit/website/src/'

# Copyright
copyright:        "Copyright (c) 2017 <a href='mailto:research-computing-support@stanford.edu'>Stanford Research Computing Center</a> &ndash;"

# Google Analytics
google_analytics: 
    - 'UA-68034405-2'
    - 'auto'


# Documentation and theme directories
docs_dir:   'src'
site_dir:   'site'
theme_dir:  'theme'

# Styling (keep empty values to avoid auto-adding the main page CSS/JS)
extra_css:
    - ''
extra_javascript: 
    - ''

# Options
extra:
    author:
      github: 'kcgthb'
      twitter: 'kilian_tw'
    version: '2.0.1'
    logo: 'images/logo_small_white.png'
    #font:
    #    text:   Lato
    #    code:   Source Code Pro
    palette:
        primary: 'su'
        accent:  'su'
       
# Extensions
markdown_extensions:
    - codehilite(css_class=code)
    - toc:
        permalink: "#"
    - admonition:


        
# Pages
pages:
    # important to keep /docs/ as /index.html is not generated by mkdocs
  - Overview:     docs/index.md
  - Connection:   docs/connection.md
  - Submit jobs:  docs/slurm.md
 
