name: check

# restricting branches prevents jobs from being run twice since
# a push to a pull request triggers two events.
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main


jobs:

  build:  # --------------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          pip install -r requirements.txt
      - run: |
          mkdocs --version
          mkdocs build --strict --verbose


  yamllint: # ----------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint


  mklint: # ----------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: avto-dev/markdown-lint@v1
        with:
          config: .markdownlintrc


  linkcheck: # -------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2


  notification: # ------------------------------------------------------------
    runs-on: ubuntu-20.04
    needs: [build, yamllint, mklint, linkcheck]
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: iRoachie/slack-github-actions@v2.0.1
        #if: env.WORKFLOW_CONCLUSION == 'failure'
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

