name: check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  CI: true
  PYTHON_VERSION: 3.x

jobs:

  build:  # --------------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: |
          pip install -r requirements.txt
      - run: |
          mkdocs --version
          mkdocs build --strict --verbose

  lint: # --------------------------------------------------------------------
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }

  notification: # ------------------------------------------------------------
    runs-on: ubuntu-latest
    needs: [build, lint]
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: iRoachie/slack-github-actions@v2.0.1
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

