name: deploy
on:
  workflow_dispatch:
  push:
    branches: 
      - main

# Environment
env:
  CI: true
  PYTHON_VERSION: 3.x

# Jobs to run
jobs:

  # Build and deploy site
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout source form GitHub
      - uses: actions/checkout@v2

      # Install Python runtime and dependencies
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install theme and dependencies
      - run: |
          pip install -r requirements.txt

      # Build site
      - env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
          
      # Send Slack notification
      - uses: iRoachie/slack-github-actions@v2.0.0
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
