name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'includes/**'
      - 'overrides/**'
      - 'src/**'

env:
  PYTHON_VERSION: 3.x

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
      - run: |
          pip install -r requirements.txt

      #- name: Install Insiders build
      #  if: github.event.repository.fork == false
      #  env:
      #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #  run: |
      #    git clone --depth 1 https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      #    pip install -e mkdocs-material-insiders
      #    cp mkdocs-material-insiders/mkdocs.yml mkdocs.yml
      #    echo "THEME_DIR=mkdocs-material-insiders/material" >> $GITHUB_ENV

      - name: Deploy site
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version

      - name: Send Slack notification
        uses: iRoachie/slack-github-actions@v2.0.0
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
