name: deploy
on:
  - push

# Environment
env:
  CI: true
  NODE_VERSION: 10.x
  PYTHON_VERSION: 3.x

# Jobs to run
jobs:

  # Build and deploy site
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:

      # Checkout source form GitHub
      - uses: actions/checkout@v2

      # Install Python runtime and dependencies
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install theme and dependencies
      - run: |
          pip install -r requirements.txt
          pip install .
          pip install \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0

      # Build documentation
      - env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
