name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yml'
      - 'requirements.txt'
      - 'includes/**'
      - 'overrides/**'
      - 'src/**'
      
env:
  PYTHON_VERSION: 3.x

jobs:
  deploy:
    name: Deploy site
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest

    env:
      GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python runtime
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Python dependency cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
          
      - name: Set MkDocs Material version
        run: echo "MKDOCS_MATERIAL_VERSION=$(cat .mkdocs-material.version)" >> $GITHUB_ENV
        
      - name: Install dependencies
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@${{ env. MKDOCS_MATERIAL_VERSION }}
          pip install -r requirements.txt
          
      - name: Build and deploy site
        run: mkdocs gh-deploy --force
        
      - name: Notify
        uses: iRoachie/slack-github-actions@v2.3.0
        if: ${{ always() }}
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
